import Link from "next/link";
import Image from "next/image";
import type { ReactNode } from "react";

// components/wimm/legal-shell.tsx
// Shared chrome for the three legal pages (privacy, terms, cookies) so they
// look and read consistently without triplicating the header/typography in
// every page.tsx. Content itself stays in each page file — this is layout
// only, not a content template.

const HEADING = "font-[family-name:var(--font-wimm-heading)]";
const MONO = "font-[family-name:var(--font-jetbrains-mono)] tracking-[0.05em]";

type LegalShellProps = {
  title: string;
  lastUpdated: string;
  children: ReactNode;
};

export function LegalShell({ title, lastUpdated, children }: LegalShellProps) {
  return (
    <main className="min-h-screen bg-[#F6FAF8]">
      {/* Minimal header — not the full marketing navbar, just a way back */}
      <div className="border-b border-[#D8E8E0] bg-white">
        <div className="max-w-[760px] mx-auto px-6 h-16 flex items-center">
          <Link
            href="/wimm"
            className="flex items-center gap-2.5"
            aria-label="Where Is My Money? home"
          >
            <Image
              src="/wimm/icon.png"
              alt="Where Is My Money?"
              width={26}
              height={26}
              className="rounded-full"
            />
            <span
              className={`${HEADING} font-semibold text-[#0E2A20] text-[14px]`}
            >
              Where Is My Money?
            </span>
          </Link>
        </div>
      </div>

      <div className="max-w-[760px] mx-auto px-6 py-16">
        <Link
          href="/wimm"
          className={`${MONO} inline-flex items-center gap-1.5 text-[11px] text-[#0F7A4E] uppercase mb-8 hover:underline`}
        >
          ← Back to Where Is My Money?
        </Link>

        <h1 className={`${HEADING} text-[2rem] font-bold text-[#0E2A20] mb-2`}>
          {title}
        </h1>
        <p className={`${MONO} text-[11px] text-[#7C9187] uppercase mb-12`}>
          Last Updated: {lastUpdated}
        </p>

        <div className="flex flex-col gap-8 text-[#3A4A42] leading-relaxed [&_h2]:font-[family-name:var(--font-wimm-heading)] [&_h2]:text-[1.25rem] [&_h2]:font-semibold [&_h2]:text-[#0E2A20] [&_h2]:mb-3 [&_h2]:mt-2 [&_ul]:list-disc [&_ul]:pl-5 [&_ul]:flex [&_ul]:flex-col [&_ul]:gap-1.5 [&_p]:leading-relaxed [&_a]:text-[#0F7A4E] [&_a]:underline">
          {children}
        </div>

        <p
          className={`${MONO} text-[10px] text-[#7C9187] leading-relaxed mt-16 pt-8 border-t border-[#D8E8E0]`}
        >
          This document was generated by PolicyGen and is provided for
          informational purposes only. It does not constitute legal advice.
          Please consult with a qualified attorney to ensure compliance with
          applicable laws.
        </p>
      </div>
    </main>
  );
}
